### ISSUE TITLE
Go to item navigates to the wrong script

### ISSUE THREAD

**Issue by mariuspopovici** [mariuspopovici/starlimsvscode#116]
When using Go to Item on this code: `DoProc("ENTERPRISE_DATA_PROVIDERS.VersionProvider.GetAbsoluteVersionSelectString");` the system navigates to a different script, called **ConversionProvider** instead of **VersionProvider***

**Comment by mariuspopovici** [comment]
Found that go to item uses the searchForItems service which performs a "like" search on the server. In this case, we actually need to match the name exactly instead of doing a like search which is normally the case if you search for partial matches.

I will add a **exactMatch** parameter to the Search service (by default not enabled). This option will be enabled for all the **Go To** commands.

**Comment by mariuspopovici** [comment]
Fixed in  #117

**Comment by MrDoe** [comment]
Yes, you are right. The 'like' was indented for the search in the navigation bar, i. e. to just enter 'biorep' to find anything with 'biorepository' in its name. For the 'go to' function we definitely need the exact match.
