### ISSUE TITLE
Make Web Service Url suffix configurable

### ISSUE THREAD

**Issue by Cmyna** [mariuspopovici/starlimsvscode#138]
Hello guys, it is so glad to find such a project. However I am facing an issue when using this extension: our STARLIMS Web service treat all http request ends with ".lims" in url as a session request, so our server returns "No cache item id provided" if no access token attached in request header. I had found that our web.config makes server accepts url ends with ".lims2" as a sessionless request, hence the extension can communicate with server normally when just change the end of url from ".lims" to ".lims2". So maybe add an extension setting item like "urlSuffix", set this item default value as ".lims", and for all http request url, set ther url string template like ${this.baseUrl}/SCM_API.<SCM Script>.${this.urlSuffix} ?

**Comment by mariuspopovici** [comment]
Hi! Have you tried adding this to the web.config file?

`<add key="HTTPServices" value="SCM_API.*"/>`

**Comment by Cmyna** [comment]
> Hi! Have you tried adding this to the web.config file?
> 
> `<add key="HTTPServices" value="SCM_API.*"/>`

Yes, I have tried to add the key. However the actual Problem comes from anther part of web.config file, in <system.web> tag:
```
<httpHandlers>
	<add verb="*" path="*.lims" type="Starlims.Server.WebServices.HttpHandler.DotLimsHandler, Starlims.Server.WebServices"/>
	<add verb="*" path="*.lims2" type="Starlims.Server.WebServices.HttpHandler.DotLimsSessionlessHandler, Starlims.Server.WebServices"/>
	<remove verb="*" path="*.config"/>
	<add verb="*" path="web.config" type="System.Web.HttpForbiddenHandler"/>
</httpHandlers>
```
It seems like a router to control which handler accepts http request. And for our system, when I access it with a URL like `starlimswebsite/SCM_API.*.lims2`, it returns the correct result instead of an error. 
I think it is also ok if if change the handler type in the first tag to `Starlims.Server.WebServices.HttpHandler.DotLimsSessionlessHandler`, unfortunately our system relies heavily on this session handler.I even saw that our script code was filled with hard-coded url requests like `*.lims`. It may be a disaster if I modify this term.
I tested those thing on my github forked project, and you can see my commited changes there. It is a small change. Maybe I can submit a pull request if it is ok ?

**Comment by mariuspopovici** [comment]
You are probably using an older runtime version because the current DotLimsHandler is checking the HTTPServices setting and will allow it as an exception if the script is listed there. In this case, using the sessionless handler can be used as a workaround. 
Please do a PR and we'll add the endpoint suffix as a setting to handle this situation. 

Thanks!!!
