### ISSUE TITLE
Can you tell me how to use this extension?

### ISSUE THREAD

**Issue by notlie** [mariuspopovici/starlimsvscode#14]
Hey,Marius!Can you tell me how to use this extension?I am a Starlims developer,I want to learn how develop this extension，I think it can help our Starlims development work。Thank you！

**Comment by notlie** [comment]
or give me some Doc Pls

**Comment by mariuspopovici** [comment]
Hey! Thanks for the interest. Right now it's still in development and the functionality is limited, meaning you can't actually use it for anything productive. The good news is that I've started working on this again and hope to soon have it at a point where it's usable.
