### ISSUE TITLE
1.2.81 cannot load scripts correctly

### ISSUE THREAD

**Issue by Je88e** [mariuspopovici/starlimsvscode#143]
![image](https://github.com/mariuspopovici/starlimsvscode/assets/51738837/5b2e80ea-03d0-40a1-9295-095ca579deab)
The new version extension has some issues in my  VS Code
When I click on a ServerScript Item in the Check out item list, it cannot be loaded correctly.Is this because I checked it out? I also found that the Application Code Behind that I checked out has the same problem.
  - ---------------Server Error---------------

Exception of type: SSLRunException
Description: Could not find script 'undefined.Comparer' with layer equal or lower than system layer id 300
Location: ServerScriptProvider.GetScriptIdByName()
Code: 0

Execution Stack:
   ServerScript.Enterprise_Data_Providers.ServerScriptProvider.getscriptidbyname() : 行号: 1253
   ServerScript.Enterprise_Data_Providers.ServerScriptProvider.getcode() : 行号: 645
   ServerScript.SCM_API.GetCode.main_ñ() : 行号: 43

----------End Server Error----------
---------------Server Error---------------

Exception of type: System.IndexOutOfRangeException
Description: 在位置 0 处没有任何行。

Execution Stack:
   ServerScript.SCM_API.GetCode.main_ñ() : 行号: 102

----------End Server Error----------

**Comment by MrDoe** [comment]
It seems that your server script category name is undefined. Is it possible that you created a new server script category without a name? If not, can you show me how it is displayed in Starlims Designer?

**Comment by Je88e** [comment]
![image](https://github.com/mariuspopovici/starlimsvscode/assets/51738837/dc8c91af-75bb-47f9-b9aa-d7370a8cd6f0)
this is the category that I have newly added, which contains some of my custom scripts.layerid is 300

**Comment by MrDoe** [comment]
Hm, this looks okay. I don't run into this issue on my version of Starlims.
Can you please check which layer ids the "Common", "SINO" and "UD_Tree" categories have? Are they all on layer 300?

**Comment by Je88e** [comment]
![image](https://github.com/mariuspopovici/starlimsvscode/assets/51738837/106b9674-ac23-4f82-8fea-3274d20dd924)

**Comment by mariuspopovici** [comment]
Can you post the output of this statement. I'm curious how the <ParentName> value is retrieved for those server scripts.

:RETURN DoProc("Enterprise_Data_Providers.CheckInProvider.GetPendingCheckins", {.F.});

**Comment by Je88e** [comment]
![image](https://github.com/mariuspopovici/starlimsvscode/assets/51738837/dc5d5136-c2ef-4a4c-8111-7f9ebe867687)
It is starlims designer output

**Comment by Je88e** [comment]
```
  <PendingCheckins>
    <CHILDID>A1340E0F-B66A-4F12-913E-ED92836C163F</CHILDID>
    <PARENTID>89C6647D-74A7-42CD-A704-B8D3DA7E98B9</PARENTID>
    <CHILDNAME>Tree_Helper</CHILDNAME>
    <PARENTNAME>UD_Tree</PARENTNAME>
    <CHECKEDOUTBY>ZHOUZJ</CHECKEDOUTBY>
    <CHILDTYPE>ServerScript</CHILDTYPE>
    <PARENTTYPE>SSC</PARENTTYPE>
    <CHECKEDOUTDATE>2023-09-21T15:52:34+08:00</CHECKEDOUTDATE>
    <SCRIPTLANGUAGE>STARLIMS</SCRIPTLANGUAGE>
    <ISSYSTEM>N</ISSYSTEM>
    <CAT_LAYERID>300</CAT_LAYERID>
    <LAYERID>300</LAYERID>
  </PendingCheckins>
``` 
Yes, the column names are uppercase.

**Comment by mariuspopovici** [comment]
Okay, I will publish a fix with hopefully should address the difference in capitalization for that column.
