### ISSUE TITLE
Show Pending Checkins

### ISSUE THREAD

**Issue by MrDoe** [mariuspopovici/starlimsvscode#42]
In Starlims Designer I often just the "Pending Checkins" tree so navigate to the forms/code I'm working on. 
<img src="https://github.com/mariuspopovici/starlimsvscode/assets/75829913/6319fa2d-0f44-47ba-b72a-9eb30e8886ee" alt="drawing" width="700"/>

My proposal would be that we add a button (or CheckBox) to the title bar which filters the tree to only show the currently checked out items. We could just pass a parameter to the GetEnterpriseItems script and call the Enterprise_Data_Providers.CheckInProvider.GetPendingCheckins procedure from there.

**Comment by mariuspopovici** [comment]
GetEnterpriseItems does not load the entire tree currently, it loads one category at a time i.e. it's called every time you expand a tree branch. It uses the selected branch's URI as a starting point to return the items on that level. 

I think we would need to add a "Pending Checkins" enterprise category. So... you would call GetEnterpriseItems with a "/PendingCheckins" URI and it would use the CheckinProvider to return the items with the appropriate URIs for each (dropping the /PendingCheckins root). The user would still need to expand each branch to get the the actual checked out items too.

This could work for Search as well. We could have a /Search path followed by the search string e.g. /Search/dsGet and it return everything that matches "%dsGet%" in all categories.

But yeah, the only drawback in using the tree, is that the tree loads collapsed by default and the user would have to dig into the tree to find their items.

**Comment by MrDoe** [comment]
Sorry, I hit the wrong button! The issue is not yet closed, but I'm working on it. I guess it'll be finished tomorrow.
