### ISSUE TITLE
Releases should be updated to the lastest version

### ISSUE THREAD

**Issue by MrDoe** [mariuspopovici/starlimsvscode#46]
The files in "Releases" for this repository seem outdated and should be updated to the lastest version.

**Comment by mariuspopovici** [comment]
I can take care of this. Also, at this point we can probably publish a version to the marketplace. We have enough features to where the extension is quite usable.

**Comment by mariuspopovici** [comment]
I would like to do a little more testing on MacOS this weekend. Sometimes there are issues with file paths, case sensitivity etc.

**Comment by mariuspopovici** [comment]
Updated releases.
Published extension to marketplace at https://marketplace.visualstudio.com/items?itemName=MariusPopovici.vscode-starlims

**Comment by mariuspopovici** [comment]
Completed
