### ISSUE TITLE
Add support for editing the form resource strings

### ISSUE THREAD

**Issue by mariuspopovici** [mariuspopovici/starlimsvscode#63]
Ability to view and change form resource strings. 
Ideas:
 A. implement a visual editor which allows viewing/changing form resources for multiple languages or...
 B. edit resources as code - retrieve them as a .json file with a simple structure and implement conversion to xml and save in the backend
```
        [
            "resourceId": "warning",
            "values": [
                {
                     "languageId": "ENG",
                     "translation": "Warning"
                },
                {
                     "languageId": "GER",
                     "translation": "Warnung"
                }
            ]
        ]
```

**Comment by MrDoe** [comment]
I'm preferring point A and I'd suggest to use a modified version of the table you used for showing the table definitions.
But at first I would download the respective form resources into a local XML or JSON file. Maybe this could be useful if someone plans to automate the translations with other tools.

Form definitions (XML) should also be editable for different languages. I'll keep that in mind for the HTML Forms editor. 
At first, a context menu command for switching the form language would be enough.

**Comment by MrDoe** [comment]
Okay, I've started to implement this by showing the form resources in the webview table.

What's still missing:
- edit form resources in the table and write them back via XML
- switch languages and show current language in title and tree node

**Comment by mariuspopovici** [comment]
Looks pretty cool. Thank you! :) 

There a few quirks that I've noticed:

1) when resources are opened it the languages dropdown defaults to the first language in the list which doesn't match the current language

![image](https://github.com/mariuspopovici/starlimsvscode/assets/6911793/16904c02-1457-4f97-9d1a-8795ef45653e)

2) It seems like it's checkin out / in the form when you switch between languages without making any changes

I'll play with it some more and see how it works.


I made a few changes in PR #121 because some of the existing functions (run data source and table schema view) were broken.
I separated the generic data view panel and the resources panels.

**Comment by MrDoe** [comment]
That's strange - in my tests the switching between languages worked flawlessly with 'English' and 'German'.
The check in and check out is necessary to switch between the languages, at least that's what Enterprise_Data_Providers.FormProvider.GetProgramaticXfdResources told me. ;-)
The table definition view also worked for me without problems.

**Comment by mariuspopovici** [comment]
I think a check in would be required if you added new resource keys or following a "Save Changes" but it should not be required to switch between languages without making any edits. 

One more thing, the "Resources" form entry needs to be retrieved in the search tree as well.
![image](https://github.com/mariuspopovici/starlimsvscode/assets/6911793/bb31082d-83ae-4380-8770-b0d8b19a0d17)
