### ISSUE TITLE
Marketplace logo

### ISSUE THREAD

**Issue by mariuspopovici** [mariuspopovici/starlimsvscode#78]
Was playing with logo design ideas for the marketplace page. How does this look?

https://www.logoai.com/logo/1396305

**Comment by MrDoe** [comment]
Nice! I played around further and came to this: https://www.logoai.com/logo/1398898

**Comment by mariuspopovici** [comment]
I like that too. Here's another one

https://www.logoai.com/logo/1400883

**Comment by mariuspopovici** [comment]
One more: https://www.logoai.com/logo/1411004

**Comment by MrDoe** [comment]
This looks also very cool. But I think mine is better because you can read the star and "LIMS" together as "STARLIMS" in one line. But yours is more compact and suitable for creating an icon.

A variation of yours: https://www.logoai.com/logo/1422578

**Comment by mariuspopovici** [comment]
Cool, let's go with that. My intention was mostly for this to serve as the extension icon. Something more compact will stand out better when you search the marketplace from VS Code.

**Comment by MrDoe** [comment]
Looks great! I also updated the activity bar icon to the star from the logo (see pull request).

The readme has now an animated gif showing some features of the extension.
