### ISSUE TITLE
Verify extension & API compatibility on activate

### ISSUE THREAD

**Issue by mariuspopovici** [mariuspopovici/starlimsvscode#85]
- Check if API version matches with the extension version on activate
- Implement an API version endpoint to help with identification
- Implement version sync in create-packages script (use version from package.json). This will write the version # string in the version API script as a variable / constant.

Future enhancement:
- automatically deploy the API .sdp (with a prompt) if API is outdated.
- implement an .sdp package upload API endpoint

**Comment by mariuspopovici** [comment]
Implemented the backend support for package import and version patching. 
Still need to implement the verification on startup. I'm on vacation and traveling until the 18th so updates will be less frequent during this time :)

**Comment by MrDoe** [comment]
All right - have a nice vacation!

**Comment by mariuspopovici** [comment]
Completed. You might see the upgrade message when launching the extension in development mode because package.json's version is always .1 behind the published version. 

For a normal installation, once you accept the upgrade, you won't see the message again.
